In [20]:
import numpy as np

In [21]:
my_lst = [1, 2, 3, 4]
arr = np.array(my_lst) #Shift + Tab before ( to see description of np.array

In [22]:
type(arr)

numpy.ndarray

In [23]:
print(arr)

[1 2 3 4]


In [24]:
arr

array([1, 2, 3, 4])

In [25]:
arr.shape

(4,)

In [26]:
## Nested Array
my_lst1 = [1, 2, 3, 4, 5]
my_lst2 = [6, 7, 8, 9, 5]
my_lst3 = [9, 7, 6, 8, 9]

arr = np.array([my_lst1, my_lst2, my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 5],
       [9, 7, 6, 8, 9]])

In [27]:
arr.shape

(3, 5)

In [28]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 9, 7],
       [6, 8, 9]])

In [29]:
arr.shape

(3, 5)

## Indexing

In [30]:
# Accessing the array element
# Index starts from 0
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[3]

4

In [32]:
## Nested Array
my_lst1 = [1, 2, 3, 4, 5]
my_lst2 = [6, 7, 8, 9, 5]
my_lst3 = [9, 7, 6, 8, 9]

arr = np.array([my_lst1, my_lst2, my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 5],
       [9, 7, 6, 8, 9]])

In [33]:
arr[:, :]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 5],
       [9, 7, 6, 8, 9]])

In [34]:
arr[0:2, :]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 5]])

In [35]:
arr[0:2, 0:2]

array([[1, 2],
       [6, 7]])